export const GET_DOCTOR_REQUEST="GET_DOCTOR_REQUEST"
export const GET_DOCTOR_SUCCESS="GET_DOCTOR_SUCCESS"
export const GET_DOCTOR_FAILURE="GET_DOCTOR_FAILURE"


export const ADD_DOCTOR_REQUEST="ADD_DOCTOR_REQUEST"
export const ADD_DOCTOR_SUCCESS="ADD_DOCTOR_SUCCESS"
export const ADD_DOCTOR_FAILURE="ADD_DOCTOR_FAILURE"